  runtime: python
  env: flex
  entrypoint: streamlit run nvd_cve_browswer.py --server.port $PORT --server.address 0.0.0.0
  env_variables:
      NVD_API_KEY: "your_api_key_here"

  runtime_config:
      operating_system: "ubuntu22"

  handlers:
    - url: /(.*)
      script: auto
      secure: always
      redirect_http_response_code: 301